delete from voters;
insert into voters (fname,lname,username,class,isadmin) values ("Abbey","Moses","agm11d","SR",0);
insert into voters (fname,lname,username,class,isadmin) values ("Jeff","Killeen","jtk12b","SR",1);
insert into voters (fname,lname,username,class,isadmin) values ("Claire","DuCanoe","cod42o","SO",0);
insert into voters (fname,lname,username,class,isadmin) values ("Marker","Pason","map21a","FR",0);
insert into voters (fname,lname,username,class,isadmin) values ("Gideon","Luck","gbl12a","JR",0);
insert into voters (fname,lname,username,class,isadmin) values ("Abstain","","","",0);
insert into voters (fname,lname,username,class,isadmin) values ("Abraham","Enriquez","axe14c","JR",0);
insert into voters (fname,lname,username,class,isadmin) values ("Emily","Adkins","gbl12a","JR",0);
insert into voters (fname,lname,username,class,isadmin) values ("Abstain","","","",0);
insert into voters (fname,lname,username,class,isadmin) values ("Matthew","Archer","mca12a","JR",0);
insert into voters (fname,lname,username,class,isadmin) values ("Abstain","","","",0);
insert into voters (fname,lname,username,class,isadmin) values ("Bret","Wheeless","bhw13a","JR",1);
insert into voters (fname,lname,username,class,isadmin) values ("Beau","Carter","cbc11a","SR",1);
delete from elections;
insert into elections (name) values ("SA 2016");
delete from candidates;
insert into candidates (electionid,voterid,position,votes) values (1,1,"President",0);
insert into candidates (electionid,voterid,position,votes) values (1,5,"President",0);
insert into candidates (electionid,voterid,position,votes) values (1,6,"President",0);
insert into candidates (electionid,voterid,position,votes) values (1,7,"Vice President",0);
insert into candidates (electionid,voterid,position,votes) values (1,8,"Vice President",0);
insert into candidates (electionid,voterid,position,votes) values (1,9,"Vice President",0);
insert into candidates (electionid,voterid,position,votes) values (1,10,"Treasurer",0);
insert into candidates (electionid,voterid,position,votes) values (1,11,"Treasurer",0);
delete from voted;
